=== navikt/skjema-avvikssystem/SPFx/src/config/forms/schema/schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "title": {
            "type": "string"
        },
        "conditionalOptions": {
            "type": "object",
            "additionalProperties": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            }
        },
        "description": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                }
            },
            "required": [
                "type",
                "content"
            ]
        },
        "pages": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "key": {
                        "type": "integer"
                    },
                    "title": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string"
                    },
                    "fields": {
                        "type": "array",
                        "items": {
                            "allOf": [
                                {
                                    "type": "object",
                                    "properties": {
                                        "key": {
                                            "type": "string"
                                        },
                                        "type": {
                                            "type": "string"
                                        },
                                        "options": {
                                            "anyOf": [
                                                {
                                                    "type": "array",
                                                    "items": {
                                                        "type": "string"
                                                    }
                                                },
                                                {
                                                    "type": "string"
                                                }
                                            ]
                                        },
                                        "required": {
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "key",
                                        "type"
                                    ]
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "choiceInfoTexts": {
                                            "type": "array",
                                            "items": {
                                                "type": "object",
                                                "properties": {
                                                    "key": {
                                                        "type": "string"
                                                    },
                                                    "text": {
                                                        "type": "string"
                                                    }
                                                },
                                                "required": [
                                                    "key",
                                                    "text"
                                                ]
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "actions": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "key": {
                                    "type": "string"
                                },
                                "label": {
                                    "type": "string"
                                },
                                "type": {
                                    "type": "string"
                                },
                                "iconProps": {
                                    "type": "object",
                                    "properties": {
                                        "iconName": {
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "iconName"
                                    ]
                                },
                                "iconPosition": {
                                    "type": "string"
                                },
                                "disabled": {
                                    "type": "string"
                                },
                                "invoke": {
                                    "type": "object",
                                    "properties": {
                                        "functionName": {
                                            "type": "string"
                                        },
                                        "params": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "type": "string"
                                            }
                                        },
                                        "conditionalInvoke": {
                                            "type": "object",
                                            "properties": {
                                                "condition": {
                                                    "type": "string"
                                                },
                                                "functionName": {
                                                    "type": "string"
                                                },
                                                "params": {
                                                    "type": "object",
                                                    "properties": {
                                                        "formName": {
                                                            "type": "string"
                                                        },
                                                        "state_values": {
                                                            "type": "string"
                                                        },
                                                        "setstate": {
                                                            "type": "string"
                                                        },
                                                        "key": {
                                                            "type": "string"
                                                        },
                                                        "value": {
                                                            "type": "string"
                                                        },
                                                        "skipPage": {
                                                            "type": "object",
                                                            "properties": {
                                                                "page": {
                                                                    "type": "integer"
                                                                },
                                                                "addtobreadcrumbs": {
                                                                    "type": "string"
                                                                }
                                                            },
                                                            "required": [
                                                                "page",
                                                                "addtobreadcrumbs"
                                                            ]
                                                        },
                                                        "bubble": {
                                                            "type": "object",
                                                            "properties": {
                                                                "showBubble": {
                                                                    "type": "boolean"
                                                                },
                                                                "bubbleTitle": {
                                                                    "type": "string"
                                                                },
                                                                "bubbleText": {
                                                                    "type": "string"
                                                                }
                                                            },
                                                            "required": [
                                                                "showBubble",
                                                                "bubbleTitle",
                                                                "bubbleText"
                                                            ]
                                                        }
                                                    },
                                                    "required": [
                                                        "formName",
                                                        "state_values",
                                                        "setstate",
                                                        "key",
                                                        "value",
                                                        "skipPage",
                                                        "bubble"
                                                    ]
                                                }
                                            },
                                            "required": [
                                                "condition",
                                                "functionName",
                                                "params"
                                            ]
                                        }
                                    },
                                    "required": [
                                        "functionName"
                                    ]
                                }
                            },
                            "required": [
                                "key",
                                "label",
                                "type",
                                "invoke"
                            ]
                        }
                    }
                },
                "required": [
                    "key",
                    "type"
                ],
                "if": {
                    "properties": {
                        "type": {
                            "const": "Input"
                        }
                    }
                },
                "then": {
                    "required": [
                        "fields"
                    ]
                }
            }
        }
    },
    "required": [
        "title",
        "conditionalOptions",
        "description",
        "pages"
    ]
}

=== navikt/skjema-avvikssystem/SPFx/src/config/forms/Personvern.json
{
    "title": "Personvern / behandling av personopplysninger",
    "conditionalOptions": {
        "Behandlingsgrunnlag": [
            "Manglende, utilstrekkelig eller feil bruk av behandlingsgrunnlag",
            "Feil bruk av samtykke (ugyldig samtykke)",
            "Overskuddsinformasjon/ innhenting og lagring av flere opplysninger enn nødvendig",
            "Annet"
        ],
        "Registrertes rettigheter": [
            "Rett til informasjon",
            "Rett til informasjon ved automatisering og profilering",
            "Rett til innsyn",
            "Rett til retting og sletting",
            "Rett til begrensning av behandling",
            "Rett til dataportabilitet",
            "Rett til å protestere",
            "Annet"
        ],
        "Databehandleravtaler": [
            "Manglende databehandleravtale",
            "Databehandler følger ikke avtalens instrukser",
            "Annet"
        ],
        "Overføring til tredjeland": [
            "Manglende gyldig overføringsgrunnlag",
            "Manglende tiltak for å sikre tilstrekkelig beskyttelse av personopplysningene",
            "Brudd på NAV's retningslinjer og prinsipper",
            "Annet"
        ],
        "Lagring/sletting": [
            "Det er ikke fastsatt lagringstid",
            "Det er ikke rutiner for sletting",
            "Personopplysningene slettes ikke",
            "Annet"
        ],
        "Manglende oversikter, vurderinger og dokumentasjon": [
            "Behandlingen er ikke registrert i Behandlingskatalogen",
            "Ikke gjennomført vurdering av personvernkonsekvenser ",
            "Tiltak fra vurdering av personvernkonsekvenser ikke fulgt opp",
            "Dokumentasjon av etterlevelseskrav ikke gjennomført ",
            "Ikke oppdatert Behandlingskatalogen",
            "Annet"
        ],
        "Bruk av bilder,lyd- og videoopptak": [
            "Kameraovervåkning på arbeidsplass",
            "Publisering av bilder, lyd- og videoopptak",
            "Annet"
        ],
        "Overvåking/kontroll av ansatte": [
            "Uberettiget innsyn i arbeidstakers e-postkasse, private filer mm.",
            "Ulovlig overvåkning/kontroll av ansatte",
            "Annet"
        ]
    },
    "description": {
        "type": "html",
        "content": "<div style='padding: 5px 10px'> <h3 style='margin-left: 15px'>Kategorier</h3> <ul> <li>Behandlingsgrunnlag</li> <li>Registrertes rettigheter</li> <li>Databehandleravtaler</li> <li>Overføring til tredjeland</li> <li>Lagring/sletting</li> <li>Manglende oversikter, vurderinger og dokumentasjon</li> <li>Bruk av bilder,lyd- og videoopptak</li> <li>Overvåking/kontroll av ansatte</li> <li>Andre uønskede hendelser</li> </ul> </div>"
    },
    "pages": [
        {
            "key": 1,
            "title": "Gjelder det en statlig eller kommunal tjeneste?",
            "type": "Input",
            "fields": [
                {
                    "key": "stateOrMunicipality",
                    "type": "Choice",
                    "options": [
                        "Statlig",
                        "Kommunal"
                    ],
                    "required": "true"
                }
            ],
            "actions": [
                {
                    "key": "previous",
                    "label": "Tilbake",
                    "type": "default",
                    "iconProps": {
                        "iconName": "ChevronLeft"
                    },
                    "invoke": {
                        "functionName": "ToFormSelection"
                    }
                },
                {
                    "key": "next",
                    "label": "Neste",
                    "type": "default",
                    "iconProps": {
                        "iconName": "ChevronRight"
                    },
                    "iconPosition": "right",
                    "disabled": "!state.values.stateOrMunicipality",
                    "invoke": {
                        "functionName": "NextPage",
                        "params": {
                            "state_pageNumber": "currentPageNumber",
                            "setstate": "currentPageNumber"
                        }
                    }
                }
            ]
        },
        {
            "key": 2,
            "title": "Hvilken kategori er denne hendelsen innenfor?",
            "type": "Input",
            "fields": [
                {
                    "key": "category",
                    "type": "ChoiceGroup",
                    "options": [
                        "Behandlingsgrunnlag",
                        "Registrertes rettigheter",
                        "Databehandleravtaler",
                        "Overføring til tredjeland",
                        "Lagring/sletting",
                        "Manglende oversikter, vurderinger og dokumentasjon",
                        "Bruk av bilder,lyd- og videoopptak",
                        "Overvåking/kontroll av ansatte",
                        "Fødselsnummer/biometriske kjennetegn",
                        "Andre uønskede hendelser"
                    ],
                    "choiceInfoTexts": [
                        {
                            "key": "Behandlingsgrunnlag",
                            "text": "Krav til at vi må ha et rettslig grunnlag for å kunne bruke persononpplysninger, eksempel lovhjemmel  eller samtykke"
                        },
                        {
                            "key": "Registrertes rettigheter",
                            "text": "Brudd på krav til ivaretakelse av brukerens eller ansattes personvernrettigheter. Feilbehandling eller ikke behandlet kravet innen de tidsfrister som er satt for saksbehandlingstid."
                        }
                    ],
                    "required": "true"
                }
            ],
            "actions": [
                {
                    "key": "previous",
                    "label": "Tilbake",
                    "type": "default",
                    "iconProps": {
                        "iconName": "ChevronLeft"
                    },
                    "invoke": {
                        "functionName": "PreviousPage",
                        "params": {
                            "state_pageNumber": "currentPageNumber",
                            "setstate": "currentPageNumber"
                        }
                    }
                },
                {
                    "key": "next",
                    "label": "Neste",
                    "type": "default",
                    "iconProps": {
                        "iconName": "ChevronRight"
                    },
                    "iconPosition": "right",
                    "disabled": "!state.values.category",
                    "invoke": {
                        "functionName": "NextPage",
                        "params": {
                            "state_pageNumber": "currentPageNumber",
                            "setstate": "currentPageNumber"
                        }
                    }
                }
            ]
        },
        {
            "key": 3,
            "title": "For å behandle innsendelsen på riktig måte trengs det noe mer detaljer rundt type hendelse:",
            "type": "Input",
            "fields": [
                {
                    "key": "categoryDetails",
                    "type": "ChoiceGroup",
                    "options": "form.conditionalOptions[state.values.category]",
                    "required": "form.conditionalOptions[state.values.category]",
                    "hidden": "!(form.conditionalOptions[state.values.category])",
                    "choiceInfoTexts": [
                        {
                            "key": "Feil bruk av samtykke (ugyldig samtykke)",
                            "text": "Brudd på kravene til et gyldig samtykke om at det skal være frivillg, spesifikt, informert, utvetydig og aktivt. Personopplysninger er blitt behandlet ut over det samtykket dekker."
                        },
                        {
                            "key": "Rett til informasjon ved automatisering og profilering",
                            "text": "Brudd på retten til særskilt informasjon om helautomatisert behandling og ev. bruk av profilering"
                        },
                        {
                            "key": "Rett til innsyn",
                            "text": "Brudd på retten til innsyn i egne personopplysninger og brudd på retten til informasjon om hva vi bruker personopplysningene til"
                        },
                        {
                            "key": "Rett til dataportabilitet",
                            "text": "Den registrerte kan på visse vilkår få sine personopplysninger flyttet til en annen virksomhet eller be om de utlevert"
                        },
                        {
                            "key": "Manglende databehandleravtale",
                            "text": "Eksterne leverandører behandler personopplysninger for NAV uten at det er inngått en skriftlig databehandleravtale"
                        },
                        {
                            "key": "Manglende gyldig overføringsgrunnlag",
                            "text": "For å kunne overføre personopplysninger til andre utenfor EU/EØS må det foreligge et særskilt overføringsgrunnlag etter GDPR"
                        },
                        {
                            "key": "Det er ikke fastsatt lagringstid",
